pull_request_rules:
  - name: Dependabot updates
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=Run successfully"
    actions:
      merge:
        method: squash
