name: CI
on: [push, pull_request]

jobs:
  run:
    name: Run successfully
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install
      run: npm i
    - name: Build
      run: npm run generate
    - name: Serve
      run: npm run serve &
    - name: Generate Screenshots
      run: npm run altimeter
